### ISSUE TITLE
minimum sdk version with manifest merger

### ISSUE THREAD

**Issue by ersin-ertan** [borjabravo10/FocusResize#2]
Error:Execution failed for task ':app:processAlphaDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.borjabravo:focusresize:1.0.0] /Users/mms/AndroidStudioProjects/MyApp/app/build/intermediates/exploded-aar/com.borjabravo/focusresize/1.0.0/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.example.library" to force usage

I'm not sure if the lib is backwards compatible(to use the override, or due your compatibility efforts), but if not then we can change the readme to state the min sdk version of 19.

**Comment by borjabravo10** [comment]
Hi @ersin-ertan 
The library has min sdk version of 19, because the custom animation in some cases it wasn't working. Sorry for the misunderstanding

I've updated the README.
