### ISSUE TITLE
Set custom height for small size

### ISSUE THREAD

**Issue by cristin** [borjabravo10/FocusResize#3]
Hi @borjabravo10,

First of all, thank you for this library. I was looking for something similar for months now. 
I have one question, can I set a specific height for the small item?
Also, can I disable fast scrolling?

Thank you!

**Comment by borjabravo10** [comment]
Hi @cristin 
You can set a specific height for the small item. In the README file you can see this:
```java
DefaultAdapter defaultAdapter = new DefaultAdapter(this, (int) getResources().getDimension(R.dimen.custom_item_height));
```
You define custom_item_height on dimens.xml. The big item is smallItem * 3. In this version you cannot define big item.

You cannot disable fast scrolling, It is the library main goal.

Thanks for the feedback,
